#!/bin/bash

outputPath=$1
cd $outputPath
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -days 36500 -out rootCA.crt \
     -subj "/C=CN/ST=SH/L=SH/O=AnyProxy/OU=Section/CN=Anyproxy SSL Proxying/emailAddress=AnyProxy@AnyProxy"
echo "============="
echo "rootCA generated at :"
pwd
echo "============="

chmod 666 rootCA.*

open .

exit 0